# SPDX-FileCopyrightText: AISEC Code Audit Team
#
# SPDX-License-Identifier: CC0-1.0

name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/picuscan
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
    - uses: actions/checkout@v7

    - uses: ./.github/actions/setup

    - name: Build package
      run: |
        uv build

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
