# SPDX-FileCopyrightText: 2026 AISEC Code Audit Team
#
# SPDX-License-Identifier: Apache-2.0

from . import ffi
from .value import ValueRef

def parse_assembly(llvmir: str) -> ModuleRef: ...
def parse_bitcode(bitcode: bytes) -> ModuleRef: ...

class ModuleRef(ffi.ObjectRef):
    def as_bitcode(self) -> bytes: ...
    def get_function(self, name: str) -> ValueRef: ...
    def verify(self) -> None: ...
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, value: str) -> None: ...
    @property
    def source_file(self) -> str: ...
    def link_in(self, other: ModuleRef, preserve: bool = ...) -> None: ...
    def clone(self) -> ModuleRef: ...
