# SPDX-FileCopyrightText: 2026 AISEC Code Audit Team
#
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from types import TracebackType
from typing import Any, Iterator

from typing_extensions import Self

class GraphDatabase:
    @classmethod
    def driver(cls, uri: str, *, auth: tuple[str, str] | Auth | None = ...) -> Neo4jDriver | BoltDriver: ...

class Auth: ...

class Driver:
    def session(self) -> Session: ...
    def close(self) -> None: ...
    def verify_connectivity(self) -> None: ...

class Neo4jDriver(Driver): ...
class BoltDriver(Driver): ...

class Session:
    def close(self) -> None: ...
    def run(self, query: str, **kwparameters: Any) -> Result: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None, /
    ) -> None: ...

class Result:
    def __iter__(self) -> Iterator[Record]: ...

class Record:
    def __getitem__(self, key: int | slice | str) -> Any: ...
