# SPDX-FileCopyrightText: AISEC Code Audit Team
#
# SPDX-License-Identifier: CC0-1.0

name: Build release image

on:
  release:
    types:
      - published

env:
  REGISTRY: ghcr.io

jobs:
  build-release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
      artifact-metadata: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Build base image
        uses: ./.github/actions/container
        with:
          registry: ${{ env.REGISTRY }}
          image-name: ${{ github.repository }}-base
          containerfile: Containerfile.base
          push: "true"
          run-e2e: "false"
          github-actor: ${{ github.actor }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build app image
        uses: ./.github/actions/container
        with:
          registry: ${{ env.REGISTRY }}
          image-name: ${{ github.repository }}
          containerfile: Containerfile
          push: "true"
          run-e2e: "true"
          base-image: ${{ github.ref_name }}
          github-actor: ${{ github.actor }}
          github-token: ${{ secrets.GITHUB_TOKEN }}