# SPDX-FileCopyrightText: AISEC Code Audit Team
#
# SPDX-License-Identifier: CC0-1.0

name: Build base and app image

on:
  push:
    branches:
      - main
    paths:
      - 'Containerfile.base'
      - .github/workflows/build-base-image.yml
  workflow_dispatch: {}        # manual trigger from the Actions tab
  schedule:
    - cron: '0 3 1 * *'        # optional: monthly rebuild for OS security updates

env:
  REGISTRY: ghcr.io

jobs:
  build-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
      artifact-metadata: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Build base image
        uses: ./.github/actions/container
        with:
          registry: ${{ env.REGISTRY }}
          image-name: ${{ github.repository }}-base
          containerfile: Containerfile.base
          push: "true"
          run-e2e: "false"
          github-actor: ${{ github.actor }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build app image
        uses: ./.github/actions/container
        with:
          registry: ${{ env.REGISTRY }}
          image-name: ${{ github.repository }}
          containerfile: Containerfile
          push: "true"
          run-e2e: "true"
          base-image: ${{ github.ref_name }}
          github-actor: ${{ github.actor }}
          github-token: ${{ secrets.GITHUB_TOKEN }}